config/routes.rb
Blaze::Application.routes.draw do

  get "/pro/(:id)" =>"home#project"
  namespace :admin do
    root :to => 'projects#index'
    resources :projects
    resources :persons
    resources :attachments
  end
  
  root :to => 'home#index'
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :img_path, :project_id
  validates :img_path, :presence => true
  belongs_to :project
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :email, :location, :name, :power 
  include Gravtastic
  gravtastic
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :detail, :home_url, :title, :github_url
  validates :description, :title, :home_url, :presence => true
  has_many :attachments, :dependent=>:destroy 
end

app/controllers/admin/attachments_controller.rb
#encoding : utf-8
class Admin::AttachmentsController < AdminController
	
	def index
  	@attachments = Attachment.all
  end

  def edit
  	@attachment = Attachment.find(params[:id])
  end

  def update
  	@attachment = Attachment.find(params[:id])
  	 if  @attachment && @attachment.update_attributes(params[:attachment])
         flash[:success] = "编号为#{@attachment.id}的广告修改成功"
         redirect_to admin_attachments_path
     else
         flash[:error] = @attachment.errors.messages.map{|k,v|k.to_s+": "+v.join(",")}.join("."+'<br/>')
         redirect_to edit_admins_attachment_path(@attachment)
    end
  end

  def destroy
     @attachment = Attachment.find(params[:id])
     if  @attachment && @attachment.destroy
         flash[:success] = "编号为#{@attachment.id}的项目删除成功"
     else
         flash[:error] = @attachment.errors.messages.map{|k,v|k.to_s+": "+v.join(",")}.join("."+'<br/>')
    end
    redirect_to admin_attachments_path
  end

  def new
    @attachment = Attachment.new
  end

  def create
     @attachment = Attachment.new(params[:attachment])
    if @attachment.save
        redirect_to admin_attachments_path
    else
        redirect_to new_admin_attachment_path
    end
    
  end
end

app/controllers/admin/persons_controller.rb
#encoding : utf-8
class Admin::PersonsController < AdminController
	
	def index
  	@persons = Person.all
  end

  def edit
  	@person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(params[:person])
    if @person.save
        redirect_to admin_persons_path
    else
        redirect_to new_admin_person_path
    end
  end

  def update
  	@person = Person.find(params[:id])
  	 if  @person && @person.update_attributes(params[:person])
         flash[:success] = "编号为#{@person.id}的广告修改成功"
         redirect_to admin_persons_path
     else
         flash[:error] = @person.errors.messages.map{|k,v|k.to_s+": "+v.join(",")}.join("."+'<br/>')
         redirect_to edit_admins_person_path(@person)
    end
  end

  def destroy
     @person = Person.find(params[:id])
     if  @person && @person.destroy
         flash[:success] = "编号为#{@person.id}的项目删除成功"
     else
         flash[:error] = @person.errors.messages.map{|k,v|k.to_s+": "+v.join(",")}.join("."+'<br/>')
    end
    redirect_to admin_persons_path
  end
end

app/controllers/admin/projects_controller.rb
#encoding : utf-8
class Admin::ProjectsController < AdminController
	
	def index
  	@projects = Project.all
  end

  def edit
  	@project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
        redirect_to admin_root_path
    else
        redirect_to new_admin_project_path
    end
  end

  def update
  	@project = Project.find(params[:id])
  	 if  @project && @project.update_attributes(params[:project])
         flash[:success] = "编号为#{@project.id}的广告修改成功"
         redirect_to admin_root_path
     else
         flash[:error] = @project.errors.messages.map{|k,v|k.to_s+": "+v.join(",")}.join("."+'<br/>')
         redirect_to edit_admins_ad_path(@project)
    end
  end

  def destroy
     @project = Project.find(params[:id])
     if  @project && @project.destroy
         flash[:success] = "编号为#{@project.id}的项目删除成功"
     else
         flash[:error] = @project.errors.messages.map{|k,v|k.to_s+": "+v.join(",")}.join("."+'<br/>')
    end
    redirect_to admin_root_path
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  USERS = {"songjiayang" => "liushan1314", "ken" => "password123"}

  before_filter :authenticate
  def index
  	@projects = Project.all
  end

  private

  def authenticate
    authenticate_or_request_with_http_digest do |username|
      USERS[username]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  	@projects = Project.all
  	@persons = Person.all
  end

  def project
  	@project = Project.find(params[:id].to_i)
  	@attachments = @project.attachments
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/admin/attachments/_form.html.slim
.form_new_edit
    .control-group
      label.control-label  图片地址:
      .controls
          =f.text_field :img_path, class:'input-xlarge'
    .control-group
      label.control-label 所属项目:
      .controls
          =f.collection_select :project_id, Project.all, :id, :title
    .form-actions
    	  = f.submit '提交', :class=>"btn btn-success"
    	  =link_to  '取消', admin_root_path,:class=>"btn btn-primary"

app/views/admin/attachments/edit.html.slim
= form_for  [:admin,@attachment], :html=>{:class=>'form-horizontal'}  do |builder| 
  =render :partial => 'form', :locals => {:f=>builder}

app/views/admin/attachments/index.html.slim
table.table.table-condensed.table-striped
      thead
      	tr
	        th="缩略图"
	        th="所属项目"
	        th.operation="操作"
      tbody

      	-for attachment in @attachments
          tr
					  td
					    =image_tag attachment.img_path
					  td
					    =link_to attachment.project.title, "/pro/#{attachment.project.id}" 
					  td class="last links"
					    ul class="inline"
					      li=link_to raw('<i class="icon-pencil"></i>'),edit_admin_attachment_path(attachment),title:'修改'
					      li=link_to raw('<i class="icon-remove"></i>'), admin_attachment_path(attachment), method: :delete, data: { confirm: 'Are you sure?' } , title: '删除'

app/views/admin/attachments/new.html.slim
= form_for  [:admin,@attachment], :html=>{:class=>'form-horizontal'}  do |builder| 
  =render :partial => 'form', :locals => {:f=>builder}

app/views/admin/persons/_form.html.slim
.form_new_edit
    .control-group
      label.control-label 用户名:
      .controls
          =f.text_field :name, class:'input-xlarge'
    .control-group
      label.control-label 邮箱:
      .controls
          =f.text_field :email, class:'input-xlarge', :rows=>"2" 
    .control-group
      label.control-label 地址:
      .controls
          =f.text_field :location, class:'input-xlarge', :rows=>"3" 
    .control-group
      label.control-label 擅长:
      .controls
          =f.text_field :power, class:'input-xlarge', :rows=>"3"   
    .form-actions
    	  = f.submit '提交', :class=>"btn btn-success"
    	  =link_to  '取消', admin_root_path,:class=>"btn btn-primary"

app/views/admin/persons/edit.html.slim
= form_for  [:admin,@person], :html=>{:class=>'form-horizontal'}  do |builder| 
  =render :partial => 'form', :locals => {:f=>builder}

app/views/admin/persons/index.html.slim
table.table.table-condensed.table-striped
      thead
      	tr
	        th="用户名"
	        th="邮箱"
	        th="地址"
	        th="擅长"
	        th.operation="操作"
      tbody

      	-for person in @persons
          tr
					  td
					    =person.name
					  td
					    =link_to person.email 
					  td
					    =link_to person.location 
					  td
					    =link_to person.power 
					  td class="last links"
					    ul class="inline"
					      li=link_to raw('<i class="icon-pencil"></i>'),edit_admin_person_path(person),title:'修改'
					      li=link_to raw('<i class="icon-remove"></i>'), admin_person_path(person), method: :delete, data: { confirm: 'Are you sure?' } , title: '删除'

app/views/admin/persons/new.html.slim
= form_for  [:admin,@person], url:admin_persons_path, :html=>{:class=>'form-horizontal'}  do |builder| 
  =render :partial => 'form', :locals => {:f=>builder}

app/views/admin/projects/_form.html.slim
.form_new_edit
    .control-group
      label.control-label 标题:
      .controls
          =f.text_field :title, class:'input-xlarge'
    .control-group
      label.control-label 简介:
      .controls
          =f.text_area :description, class:'input-xlarge', :rows=>"2" 
    .control-group
      label.control-label 详情:
      .controls
          =f.text_area :detail, class:'input-xlarge', :rows=>"3" 
    .control-group
      label.control-label home:
      .controls
          =f.text_field :home_url, class:'input-xlarge', :rows=>"3"   
    .control-group
      label.control-label github:
      .controls
          =f.text_field :github_url, class:'input-xlarge', :rows=>"3" 
    .form-actions
    	  = f.submit '提交', :class=>"btn btn-success"
    	  =link_to  '取消', admin_root_path,:class=>"btn btn-primary"

app/views/admin/projects/_projects.html.slim
tr
  td
    =project.title
  td
    =project.description
  td
    =project.detail
  td
    =link_to project.home_url, project.home_url
  td class="last links"
    ul class="inline"
      li
        =link_to raw('i class="icon-pencil"/i'),edit_admin_project_path(project),title:'修改'
      li
        =link_to raw('i class="icon-info-sign"/i'),"",title:'查看'
      li
        =link_to raw('i class="icon-remove"/i'), "", method: :delete, data: { confirm: 'Are you sure?' } , title: '删除'

app/views/admin/projects/edit.html.slim
= form_for  [:admin,@project], :html=>{:class=>'form-horizontal'}  do |builder| 
  =render :partial => 'form', :locals => {:f=>builder}

app/views/admin/projects/index.html.slim
table.table.table-condensed.table-striped
      thead
      	tr
	        th.title="标题"
	        th.description="简介"
	        th.detail="详情"
	        th.url=" 演示地址"
	        th.operation="操作"
      tbody

      	-for project in @projects
          tr
					  td
					    =project.title
					  td
					    =project.description
					  td
					    =project.detail
					  td
					    =link_to project.home_url, project.home_url
					  td class="last links"
					    ul class="inline"
					      li=link_to raw('<i class="icon-pencil"></i>'),edit_admin_project_path(project),title:'修改'
					      li=link_to raw('<i class="icon-remove"></i>'), admin_project_path(project), method: :delete, data: { confirm: 'Are you sure?' } , title: '删除'

app/views/admin/projects/new.html.slim
= form_for  [:admin,@project], :html=>{:class=>'form-horizontal'}  do |builder| 
  =render :partial => 'form', :locals => {:f=>builder}

app/views/home/index.html.slim
<!-- BEGIN: header -->
#header-wrap
	.logo
		 span BLAZE  
	#header
		.top-menu
			ul.menu
				li
					a href="#home" class="nav_home current" Home
				li
					a href="#skills" class="nav_what " Skills
				li
					a href="#members" class="nav_register" Members
				li
					a href="#contact" class="nav_register" Contact
				li
					a href="/" class="nav_register" Blog
.clear
.double-line

<!-- BEGIN: home page -->
.scrol-page.black#home
		section#title
			.page_caption
				h1  WHAT WE DODN
		.container#slogan-container
			#slogan
				p.teaserHeavy JUST THINK ABOUT "WHO" TO SEND,<br>FUSTEENO TAKE CARE "WHERE"
			.marketing.center
				- for project in @projects do 
					.span3
						.projects
							  img src=project.attachments.first.img_path id=project.id
						 	  p.title  
						 	  	a href="/pro/#{project.id}" =project.title 
						 	  p class='description'  =project.description
							
.clear
<!-- BEGIN: what is page -->
.scrol-page.black#skills
		section#title
			.page_caption
				h1 WHAT WE USE
		.container#slogan-container
			#slogan
				p.teaserHeavy JUST THINK ABOUT "WHO" TO SEND,<br>FUSTEENO TAKE CARE "WHERE"	
			.marketing
				.row-fluid.skills-img
					.span9
							  <img src="/img/skills/rails.png">
.clear
<!-- BEGIN: what is page -->
.scrol-page.black#members
		section#title
			.page_caption
				h1 WHO WE ARE
		.container#slogan-container
			#slogan
				p.teaserHeavy JUST THINK ABOUT "WHO" TO SEND,<br>FUSTEENO TAKE CARE "WHERE"	
			.marketing
			.members.center
				-@persons.each_with_index do |person,index| 
					.span5.person
							=image_tag person.gravatar_url
							.details
								p 
									span.icon-user.user
									=person.name
								p 
									span.icon-envelope
									=person.email
								p 
								  span.icon-map-marker
								  =person.location
								p 
									span.icon-eye-open
									=person.power

.clear	
#contact.scrol-page
	a href="mailto:info"
		section#title 
	section#title
		.page_caption
			h1 
				a href="mailto:info@fusteeno.com"
					 img src="/img/tell.png" width="274" height="197"
			h2
				a href="mailto:info@fusteeno.com" Comments and suggestions? contact us!<br>
				a href="mailto:info@fusteeno.com" Advertise with us? contact us! 
.clear

	.copyright
		p Copyright  © 2013 fusteeno. All rights reserved.<br> Google™, dropbox™, facebook™ and its logos are registered trademarks.
		p   
  
															

app/views/home/project.html.slim
<!-- BEGIN: header -->
#project-header-wrap
  .inner
    a.my-logo href="/" Blaze For Your Best
    h1 =@project.title
    h2 =@project.description
section.main
    .span2
    .inner.span8
      .l
        p.cover-section
          img src=@attachments.first.img_path
        .project-description
          p =@project.detail
        .project-links
          a.extrudedbtn href=@project.home_url 
            span Project Home
          a.extrudedbtn href=@project.github_url
            span View On Github

      .r
        .gallery
          .scroll-thumbs
            ul.thumbs.project-img
              -@attachments.each_with_index do |attachment,index|
                li
                  img class=('act' if index==0) src=attachment.img_path
          .show-box
            img src=@attachments.first.img_path
.clear
.two_line
.copyright
    p Copyright  © 2013 fusteeno. All rights reserved.<br> Google™, dropbox™, facebook™ and its logos are registered trademarks.
    p   




                              

app/views/layouts/admin.html.slim
doctype html
html
  head
    title Blaze
    meta name="keywords" content="template language"
    meta name="Blaze"
    == stylesheet_link_tag    "application", :media => "all"
    == javascript_include_tag "application"
    == csrf_meta_tags 

  body
  .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          a.btn.btn-navbar data-toggle="collapse" data-target=".nav-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="/" Blaze后台管理
          .nav-collapse
            ul.nav
              li.dropdown class=('active' if controller_name=='projects')
                  a.dropdown-toggle data-toggle="dropdown" href="#fat"  Porojects <b class='caret'></b>
                  ul.dropdown-menu  
                     li 
                       a href="/admin" 项目列表
                     li 
                       a href="/admin/projects/new" 新增项目
              li.dropdown  class=('active' if controller_name=='attachments' )
                  a.dropdown-toggle data-toggle="dropdown" href="#fat" Attachments <b class='caret'></b>
                  ul.dropdown-menu  
                     li 
                       a href="/admin/attachments" 图片列表
                     li 
                       a href="/admin/attachments/new" 新增图片

              li.dropdown class=('active' if controller_name=='persons')
              	  a.dropdown-toggle data-toggle="dropdown" href="#fat" Persons <b class='caret'></b>
                  ul.dropdown-menu  
                     li 
                       a href="/admin/persons" 人员列表
                     li 
                       a href="/admin/persons/new" 新增人员
          p.pull-right.logout  退出
.container
  .span8.admin-form
		== yield   

app/views/layouts/application.html.slim
doctype html
html
  head
    title Blaze
    meta name="keywords" content="template language"
    meta name="Blaze"
    == stylesheet_link_tag    "application", :media => "all"
    == javascript_include_tag "application"
    == csrf_meta_tags 

  body
		== yield   